#include "robot_importer_gui/LaunchGenerator.hh"

namespace robot_importer_gui
{

namespace
{

static QString nsArg(const QString &ns)
{
  if (ns.trimmed().isEmpty()) return {};
  const QString n = ns.startsWith('/') ? ns : '/' + ns;
  return QStringLiteral("        namespace='%1',\n").arg(n);
}

static QString nsCli(const QString &ns)
{
  if (ns.trimmed().isEmpty()) return {};
  const QString n = ns.startsWith('/') ? ns : '/' + ns;
  return QStringLiteral(" -r __ns:=%1").arg(n);
}

}  // namespace

// ============================================================
QString LaunchGenerator::bridgeCommand(const RuntimeFindings &findings,
                                       const QString &rosNamespace)
{
  QStringList specs;
  for (const SensorFindings &s : findings.sensors)
  {
    if (s.needsBridge && s.bridge.confidence != QLatin1String("manual_review"))
      specs << s.bridge.paramBridgeArg();
  }
  if (specs.isEmpty()) return {};

  QString cmd = QStringLiteral("ros2 run ros_gz_bridge parameter_bridge");
  // Add namespace remapping if set.
  const QString ns = rosNamespace.trimmed();
  if (!ns.isEmpty())
  {
    const QString n = ns.startsWith('/') ? ns : '/' + ns;
    cmd += QStringLiteral(" --ros-args -r __ns:=%1 --").arg(n);
  }
  for (const QString &sp : specs)
    cmd += QStringLiteral(" \\\n  \"%1\"").arg(sp);
  return cmd;
}

// ============================================================
QString LaunchGenerator::launchFileContent(
    const RuntimeFindings &findings,
    const QString &instanceName,
    const QString &rosNamespace)
{
  const QString ns   = rosNamespace.trimmed();
  const QString nsA  = nsArg(ns);
  const bool hasCtrl = findings.hasRos2Control;
  const bool hasSens = findings.hasSensorPlugins || findings.hasOtherRosPlugins;

  // Collect bridge specs.
  QStringList bridgeArgs;
  for (const SensorFindings &s : findings.sensors)
    if (s.needsBridge && s.bridge.confidence != QLatin1String("manual_review"))
      bridgeArgs << s.bridge.paramBridgeArg();

  QString header;
  header += QStringLiteral("# Auto-generated by Robot Importer\n");
  header += QStringLiteral("# Model: %1\n").arg(instanceName);
  if (hasCtrl)
    header += QStringLiteral("# Detected: ros2_control\n");
  if (hasSens || !bridgeArgs.isEmpty())
    header += QStringLiteral("# Detected: ROS 2 sensor/plugin integration\n");
  if (findings.hasXacroControlArgs)
    header += QStringLiteral("# XACRO control args: %1\n")
        .arg(findings.xacroControlArgs.join(QLatin1String(", ")));
  if (findings.hasUnresolvedRuntimeItems)
    header += QStringLiteral("# WARNING: some sensors could not be fully resolved — review bridge specs.\n");
  header += QStringLiteral("# Edit controller names and robot_description to match your robot.\n#\n");

  QString imports;
  imports += QStringLiteral("from launch import LaunchDescription\n");
  imports += QStringLiteral("from launch_ros.actions import Node\n\n\n");

  QString body;
  body += QStringLiteral("def generate_launch_description():\n");
  body += QStringLiteral("    return LaunchDescription([\n");

  // ros_gz_bridge node for native sensor bridges.
  if (!bridgeArgs.isEmpty())
  {
    body += QStringLiteral("        # ros_gz_bridge — bridges native Gazebo sensor topics to ROS 2\n");
    body += QStringLiteral("        Node(\n");
    body += QStringLiteral("            package='ros_gz_bridge',\n");
    body += QStringLiteral("            executable='parameter_bridge',\n");
    body += nsA;
    body += QStringLiteral("            arguments=[\n");
    for (const QString &arg : bridgeArgs)
      body += QStringLiteral("                '%1',\n").arg(arg);
    body += QStringLiteral("            ],\n");
    body += QStringLiteral("            output='screen',\n");
    body += QStringLiteral("        ),\n");
  }

  if (hasCtrl)
  {
    if (!bridgeArgs.isEmpty()) body += QStringLiteral("\n");
    body += QStringLiteral("        # ros2_control node — manages hardware interfaces\n");
    body += QStringLiteral("        Node(\n");
    body += QStringLiteral("            package='controller_manager',\n");
    body += QStringLiteral("            executable='ros2_control_node',\n");
    body += nsA;
    body += QStringLiteral("            output='screen',\n");
    body += QStringLiteral("            parameters=[{\n");
    body += QStringLiteral("                'use_sim_time': True,\n");
    body += QStringLiteral("                # 'robot_description': open('/path/to/robot.urdf').read(),\n");
    body += QStringLiteral("            }],\n");
    body += QStringLiteral("        ),\n");

    body += QStringLiteral("        # joint_state_broadcaster — publishes /joint_states\n");
    body += QStringLiteral("        Node(\n");
    body += QStringLiteral("            package='controller_manager',\n");
    body += QStringLiteral("            executable='spawner',\n");
    body += nsA;
    body += QStringLiteral("            arguments=['joint_state_broadcaster',\n");
    body += QStringLiteral("                       '--controller-manager', '/controller_manager'],\n");
    body += QStringLiteral("            output='screen',\n");
    body += QStringLiteral("        ),\n");
    body += QStringLiteral("        # Node(package='controller_manager', executable='spawner',\n");
    body += QStringLiteral("        #      arguments=['your_controller_name']),\n");
  }

  if (hasSens && !hasCtrl && bridgeArgs.isEmpty())
  {
    body += QStringLiteral("        # robot_state_publisher — broadcasts TF from joint_states\n");
    body += QStringLiteral("        Node(\n");
    body += QStringLiteral("            package='robot_state_publisher',\n");
    body += QStringLiteral("            executable='robot_state_publisher',\n");
    body += nsA;
    body += QStringLiteral("            output='screen',\n");
    body += QStringLiteral("            parameters=[{'use_sim_time': True}],\n");
    body += QStringLiteral("        ),\n");
  }

  if (!hasCtrl && !hasSens && bridgeArgs.isEmpty())
    body += QStringLiteral("        # Add nodes required by your robot here.\n");

  body += QStringLiteral("    ])\n");
  return header + imports + body;
}

// ============================================================
QString LaunchGenerator::launchCommand(
    const RuntimeFindings &findings,
    const QString &instanceName,
    const QString &rosNamespace)
{
  // Bridge command takes priority when native sensors need bridging.
  const QString bridge = bridgeCommand(findings, rosNamespace);
  if (!bridge.isEmpty()) return bridge;

  Q_UNUSED(instanceName);
  const QString ns   = rosNamespace.trimmed();
  const QString nsCl = nsCli(ns);

  if (findings.hasRos2Control)
    return QStringLiteral(
        "ros2 run controller_manager ros2_control_node"
        " --ros-args%1 -p use_sim_time:=true").arg(nsCl);

  if (findings.hasSensorPlugins || findings.hasOtherRosPlugins)
    return QStringLiteral(
        "ros2 run robot_state_publisher robot_state_publisher"
        " --ros-args%1 -p use_sim_time:=true").arg(nsCl);

  return QStringLiteral(
      "ros2 launch <your_package> <your_robot>.launch.py use_sim_time:=true");
}

}  // namespace robot_importer_gui
