#include "robot_importer_gui/LaunchGenerator.hh"

namespace robot_importer_gui
{

namespace
{

// Returns "  namespace='<ns>'," indented for use inside a Node() call,
// or an empty string when no namespace is set.
static QString nsArg(const QString &ns)
{
  if (ns.trimmed().isEmpty()) return {};
  // Ensure leading slash.
  const QString n = ns.startsWith('/') ? ns : '/' + ns;
  return QStringLiteral("        namespace='%1',\n").arg(n);
}

// Returns "-r __ns:=/<ns>" for inline CLI use, or empty string.
static QString nsCli(const QString &ns)
{
  if (ns.trimmed().isEmpty()) return {};
  const QString n = ns.startsWith('/') ? ns : '/' + ns;
  return QStringLiteral(" -r __ns:=%1").arg(n);
}

}  // namespace

// ============================================================
QString LaunchGenerator::launchFileContent(
    const RuntimeFindings &findings,
    const QString &instanceName,
    const QString &rosNamespace)
{
  const QString ns   = rosNamespace.trimmed();
  const QString nsA  = nsArg(ns);   // Node() keyword argument, indented
  const bool hasCtrl = findings.hasRos2Control;
  const bool hasSens = findings.hasSensorPlugins || findings.hasOtherRosPlugins;

  QString header;
  header += QStringLiteral("# Auto-generated by Robot Importer\n");
  header += QStringLiteral("# Model: %1\n").arg(instanceName);

  if (hasCtrl)
    header += QStringLiteral("# Detected: ros2_control\n");
  if (hasSens)
    header += QStringLiteral("# Detected: ROS 2 sensor/plugin integration\n");
  if (findings.hasXacroControlArgs)
  {
    header += QStringLiteral("# XACRO control args: %1\n")
        .arg(findings.xacroControlArgs.join(QLatin1String(", ")));
  }
  header += QStringLiteral("# Edit controller names and robot_description to match your robot.\n");
  header += QStringLiteral("#\n");

  QString imports;
  imports += QStringLiteral("from launch import LaunchDescription\n");
  imports += QStringLiteral("from launch_ros.actions import Node\n");
  imports += QStringLiteral("\n\n");

  QString body;
  body += QStringLiteral("def generate_launch_description():\n");
  body += QStringLiteral("    return LaunchDescription([\n");

  if (hasCtrl)
  {
    body += QStringLiteral("        # ros2_control node — manages hardware interfaces\n");
    body += QStringLiteral("        Node(\n");
    body += QStringLiteral("            package='controller_manager',\n");
    body += QStringLiteral("            executable='ros2_control_node',\n");
    body += nsA;
    body += QStringLiteral("            output='screen',\n");
    body += QStringLiteral("            parameters=[{\n");
    body += QStringLiteral("                'use_sim_time': True,\n");
    body += QStringLiteral("                # Provide robot_description or point to a YAML config:\n");
    body += QStringLiteral("                # 'robot_description': open('/path/to/robot.urdf').read(),\n");
    body += QStringLiteral("            }],\n");
    body += QStringLiteral("        ),\n");

    body += QStringLiteral("        # joint_state_broadcaster — publishes /joint_states\n");
    body += QStringLiteral("        Node(\n");
    body += QStringLiteral("            package='controller_manager',\n");
    body += QStringLiteral("            executable='spawner',\n");
    body += nsA;
    body += QStringLiteral("            arguments=['joint_state_broadcaster',\n");
    body += QStringLiteral("                       '--controller-manager', '/controller_manager'],\n");
    body += QStringLiteral("            output='screen',\n");
    body += QStringLiteral("        ),\n");

    body += QStringLiteral("        # Add more controller spawners as needed:\n");
    body += QStringLiteral("        # Node(\n");
    body += QStringLiteral("        #     package='controller_manager',\n");
    body += QStringLiteral("        #     executable='spawner',\n");
    if (!nsA.isEmpty())
    {
      QString commentedNs = nsA;
      commentedNs.replace(QLatin1String("        "), QLatin1String("        #     "));
      body += commentedNs;
    }
    body += QStringLiteral("        #     arguments=['your_controller_name'],\n");
    body += QStringLiteral("        # ),\n");
  }

  if (hasSens)
  {
    if (hasCtrl) body += QStringLiteral("\n");
    body += QStringLiteral("        # robot_state_publisher — broadcasts TF from joint_states\n");
    body += QStringLiteral("        Node(\n");
    body += QStringLiteral("            package='robot_state_publisher',\n");
    body += QStringLiteral("            executable='robot_state_publisher',\n");
    body += nsA;
    body += QStringLiteral("            output='screen',\n");
    body += QStringLiteral("            parameters=[{\n");
    body += QStringLiteral("                'use_sim_time': True,\n");
    body += QStringLiteral("                # 'robot_description': open('/path/to/robot.urdf').read(),\n");
    body += QStringLiteral("            }],\n");
    body += QStringLiteral("        ),\n");
  }

  if (!hasCtrl && !hasSens)
  {
    // Fallback for hasXacroControlArgs-only case
    body += QStringLiteral("        # Add nodes required by your robot here.\n");
  }

  body += QStringLiteral("    ])\n");

  return header + imports + body;
}

// ============================================================
QString LaunchGenerator::launchCommand(
    const RuntimeFindings &findings,
    const QString &instanceName,
    const QString &rosNamespace)
{
  Q_UNUSED(instanceName);
  const QString ns = rosNamespace.trimmed();
  const QString nsCl = nsCli(ns);

  if (findings.hasRos2Control)
  {
    // Primary command: start controller_manager.
    // The user needs to spawner controllers separately.
    return QStringLiteral(
        "ros2 run controller_manager ros2_control_node"
        " --ros-args%1 -p use_sim_time:=true").arg(nsCl);
  }

  if (findings.hasSensorPlugins || findings.hasOtherRosPlugins)
  {
    return QStringLiteral(
        "ros2 run robot_state_publisher robot_state_publisher"
        " --ros-args%1 -p use_sim_time:=true").arg(nsCl);
  }

  // xacro control args only (no plugin match) — generic fallback
  return QStringLiteral(
      "ros2 launch <your_package> <your_robot>.launch.py"
      " use_sim_time:=true");
}

}  // namespace robot_importer_gui
